### ISSUE TITLE
Linux: Simulator only works if system language is set to English

### ISSUE THREAD

**Issue by wAuner** [udacity/self-driving-car-sim#59] opened 2017-11-14 09:48 UTC
When using a language other than English for your linux system (tested with German) the simulator does not work properly. 
![bildschirmfoto vom 2017-11-13 16-05-43](https://user-images.githubusercontent.com/18383180/32773229-b7bdc3fa-c928-11e7-8471-7767ccfefe11.png)
The result is a simulator with no visible datapoints and the udacity logo on the car is jumping around. 
If you connect a working (correctly implemented) Filter, the RMSE explodes.
I guess this has something to do with the way the data is read. Probably due to some formatting error the datapoints don't appear on the screen if the system language is not English.
Tested this with KDE Neon, Linux Mint 18.2 and Ubuntu 16.04 LTS.

Switching the system language in the preferences to English doesn't solve the problem, but the simulator works correctly.

**Comment by mreichelt** [comment] 2017-11-14 11:08
Should be closed, duplicate of #6

**Comment by wAuner** [comment] 2017-11-14 11:12
you‘re right it‘s a duplicate. however this title could help others with that problem, since this problem isn‘t described in the lessons.

**Comment by baumanab** [comment] 2018-02-19 07:58
Sorry for this issue.  A note has been added to the simulator release notes, regarding the issue, and its solution.

**Closed by baumanab** 2018-02-19 07:58 UTC
